[appendix]
== Configuration

simple-jpa can be configured by adding configuration lines in +griffon-app/conf/Config.groovy+. Adding JPA provider
properties can also be done directly by editing +griffon-app/conf/metainf/persistence.xml+ or by using system
properties.

=== Domain Package

simple-jpa doesn't use any metadata to manage domain classes. The only way for simple-jpa to find or to write domain
classes is by inspecting the content of domain package. All domain classes should be located in this domain package.
By default, the name of domain package is +domain+.

Developer can change the name of domain package by using this configuration line. For example, the following
configuration change the name of domain package to +com.example.domain+:

[source,groovy]
----
griffon.simplejpa.domain.package='com.example.domain'
----

WARNING: Changing this configuration value will not move existing domain classes to the new domain package. This value
merely used as an indicator to find domain classes.

=== Default Flush Mode

Use this configuration key to change the default +flushMode+ for all EntityManager in application. The possible values
for flushMode is +'COMMIT'+ and +'AUTO'+. The default value for +flushMode+ is depends on JPA provider.

For example, the following configuration line will set +flushMode+ for all EntityManager to +DefaultFlushModeType.COMMIT+:

[source,groovy]
----
griffon.simplejpa.entityManager.defaultFlushMode = 'COMMIT'
----

Default flushMode can be overriden in certain queries by using +flushMode+ query configuration.

=== Entity Manager Properties

In most cases, JPA properties can be added directly to +griffon-app/conf/metainf/persistence.xml+. The following is
content of a typical +persistence.xml+ file for desktop application:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?><persistence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://java.sun.com/xml/ns/persistence" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd" version="2.0">
  <persistence-unit name="default" transaction-type="RESOURCE_LOCAL">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <class>domain.Student</class>
    <class>domain.Classroom</class>
    <properties>
      <property name="javax.persistence.jdbc.driver" value="com.mysql.jdbc.Driver"/>
      <property name="javax.persistence.jdbc.url" value="jdbc:mysql://localhost/mydatabase"/>
      <property name="javax.persistence.jdbc.user" value="scott"/>
      <property name="javax.persistence.jdbc.password" value="tiger"/>
      <property name="hibernate.connection.autocommit" value="false"/>
      <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect"/>
      <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
      <property name="jadira.usertype.autoRegisterUserTypes" value="true"/>
    </properties>
  </persistence-unit>
</persistence>
----

Developer can override properties in +persistence.xml+ by adding configuration line with
+griffon.simplejpa.entityManager.properties+ key. For example, the following configuration will result in the same
JPA properties as above:

[source,groovy]
----
griffon {
    simplejpa {
        entityManager {
            properties  {
                javax.persistence.jdbc.driver = 'com.mysql.jdbc.Driver'
                javax.persistence.jdbc.url = 'jdbc:mysql://localhost/mydatabase'
                javax.persistence.jdbc.user = 'scott'
                javax.persistence.jdbc.password = 'tiger'
                hibernate.connection.autocommit = 'false'
                hibernate.dialect = 'org.hibernate.dialect.MySQL5Dialect'
                jadira.usertype.autoRegisterUserTypes=  'true'
            }
        }
    }
}
----

Another way to override JPA provider properties is by writing the properties in a file called +simplejpa.properties+.
Content of the file is in Groovy's config format just like the one specified in +Config.groovy+. simple-jpa will search
for this file in current working directory. If the file exists, its content will override properties in
+persistence.xml+ and +Config.groovy+.

This is a convenient way to modify JPA properties without changing source code. It is common to put database connection
properties in +simplejpa.properties+ so that changing database connection will not require touching application's source
code.

The following is sample content of +simplejpa.properties+:

[source,groovy]
----
javax {
    persistence {
        jdbc {
            driver = 'com.mysql.jdbc.Driver'
            url = 'jdbc:mysql://localhost/mydatabase'
            user = 'scott'
            password = 'tiger'
        }
    }
}
hibernate {
    connection {
	autocommit = 'false'
    }
    dialect = 'org.hibernate.dialect.MySQL5Dialect'
}
jadira.usertype.autoRegisterUserTypes=  'true'
----

Developer can change location and name of the +simplejpa.properties+ by adding +griffon.simplejpa.entityManager.propertiesFile+
configuration line. For example, in the following configuration, simple-jpa will search for a file called +connection.db+
in root directory of drive C:

[source]
----
griffon.simplejpa.entityManager.propertiesFile = 'C:/connection.db'
----

=== Soft Delete

If the value for this configuration key is +true+, simple-jpa finders will not return soft deleted objects. A soft
deleted object is an object whose deleted attribute is not equals to +'N'+. The deleted attribute is available on all
domain classes that have +@DomainClass+ annotation. To soft delete an domain object, use +softDelete()+ method.

Note that developer can still retrieve soft deleted objects by using +executeQuery()+, +executeNativeQuery()+, or
passing +false+ to +excludeDeleted+ query configuration.

By default, the value for this configuration key is +false+. To enable it, add the following line to +Config.groovy+:

[source]
----
griffon.simplejpa.finders.alwaysExcludeSoftDeleted = true
----

=== Finders

By default, simple-jpa will inject JPA related methods such as finders to all Griffon's controllers. This causes all
controllers to act as public repositories with the abilities to retrieve arbitary domain objects. While this pattern
reduces complexity, some people may want to appoint service layer as repository layer (instead of controllers as
repositories). This can be achieved by adding the following configuration line:

[source, grooovy]
----
griffon.simplejpa.finders.injectInto = ['service']
----

The following examples will cause simple-jpa to inject JPA related methods to all controllers and all models:

[source, groovy]
----
griffon.simplejpa.finders.injectInto = ['controller', 'model']
----

To avoid conflict with existing methods in controller, simple-jpa can add prefix to its dynamic methods. For example,
the following configuration line will add jpa prefix to simple-jpa dynamic methods:

[source, groovy]
----
griffon.simplejpa.finders.prefix = 'jpa'
// This will add 'jpa' prefix to dynamic methods name, for example:
// findAllStudent() becomes jpaFindAllStudent()
----

The following dynamic methods will never have prefix:

* +beginTransaction()+
* +commitTransaction()+
* +rollbackTransaction()+
* +return_failed()+
* +createEntityManager()+
* +destroyEntityManager()+
* +getEntityManager()+

Since simple-jpa 0.7, by default, duplicate entities returned by finders will be ignored. To allow finders to return
duplicate entities, add the following line:

[source,groovy]
----
griffon.simplejpa.finders.alwaysAllowDuplicate = true
----

=== Validation

In some cases, validation may be failed because the empty JTextField value in model is an empty String and not a null
value. To create a consistent behaviour, simple-jpa can translate all empty String into a null value before performing
validation. This feature is disabled by default. To enable it, add the following configuration line:

[source,groovy]
----
griffon.simplejpa.validation.convertEmptyStringToNull = true
----

=== Auditing

To display a login dialog at startup time, set a service name for `griffon.simplejpa.auditing.loginService`.  This service must be an
instance of `org.jdesktop.swingx.auth.LoginService`.

[source,groovy]
.Config.groovy
----
griffon.simplejpa.auditing.loginService = 'DatabaseLoginService'
----

