[appendix]
== Annotation

These annotations are using Groovy AST transformation feature to change the content of a class dynamically on compile.

=== @ConditionSupport

Adding +@ConditionSupport+ annotation to a Swing +TableCellRenderer+ will make the renderer ready to use with
+condition()+ node.

Example:

[source,groovy]
----
@ConditionSupport
class MyCustomRenderer extends DefaultTableCellRenderer {
   ...
}
----

=== @DomainClass

This annotation is supposed to be used on domain class, for example:

[source,groovy]
----
@DomainClass
class Student {

}
----

+@DomainClass+ annotation will add the following attribute to the annotated class:

[source,groovy]
----
@Id @GeneratedValue(strategy=GenerationType.TABLE)
Long id

String deleted = 'N'

Date createdDate

Date modifiedDate
----

+@DomainClass+ will not add the attributes above if the annotated class is a subclass of another class which is
annotated by +@DomainClass+ or +@Entity+.

To skip adding +id+ attribute, set +excludeId+ to +true+.

To skip adding +deleted+ attribute, set +excludeDeletedFlag+ to +true+.

To skip adding +createdDate+ and +modifiedDate+ attribute, set +excludeAuditing+ to +true+. For example, the following
annotation will only add +id+ to the annotated class:

[source,groovy]
----
@DomainClass(excludeDeletedFlag=true, excludeAuditing=true)
class Student {

}
----

By default, the id generation strategy is +GenerationType.TABLE+. To change the default generation strategy, use
+idGenerationStrategy+ member. For example, the following annotation will add an +id+ attribute whose value is generated
by using database identity column (auto increment field):

[source,groovy]
----
@DomainClass(idGenerationStrategy=GenerationType.IDENTITY)
class Student {

}
----

Warning: This annotation only add attributes to annotated class. Using this annotation on a class doesn't mean that
simple-jpa will register it in +persistence.xml+. Even when a class is annotated with +@DomainClass+, if it is not
located in domain package, finders will not recognize it.

=== @Transaction

+@Transaction+ annotation can be used to annotate a class, a closure field, or a method. It will cause the method or
closure to be wrapped in database transaction. Using +@Transaction+ on a class will make all execution of methods or
closure fields in the class to be wrapped in database transaction. If there are both +@Transaction+ annotation in a
method/closure field and its class, only annotation in method will be used.

+@Transaction+ can only be used in Griffon's artifact (controllers or services) and domain classes (must be located
inside +griffon.simplejpa.domain.package+).

+@Transaction+ annotation value can be one of +Policy.NORMAL+, +Policy.SKIP_PROPAGATION+, and +Policy.SKIP+. The
default value is +Policy.NORMAL+.

A +Policy.NORMAL+ transaction will join the previous transaction if it is called from another transaction. This will
enable transaction propagation. For example, the following code will not save any objects to database because
+processA()+, +processB()+, and +processC()+ is part of one transaction and if any of them fails, all operations will
rollback:

[source,groovy]
----
@Transaction
class AController {

    def processC() {
    	throw new RuntimeException("Suddenly there is an error here!")
    }

    def processB() {
    	ADomainClass b = new ADomainClass()
        persist(b)
        processC()
    }

    def processA() {
    	ADomainClass a = new ADomainClass()
        persist(a)
        processB()
    }

}
----

A +Policy.SKIP_PROPAGATION+ transaction will always start a new transaction. It will not join previous transaction.
For example, the following code will result in +a+ being persisted in database but +b+ will be ignored:

[source,groovy]
----
@Transaction
class AController {

    @Transaction(Transaction.Policy.SKIP_PROPAGATION)
    def processB() {
    	ADomainClass b = new ADomainClass()
        persist(b)
        processC()
    }

    def processA() {
    	ADomainClass a = new ADomainClass()
        persist(a)
        processB()
    }

}
----

A +Policy.SKIP+ transaction mean there is no transaction at all (+@Transaction+ will do nothing). It is recommended to
use this attribute to method or closure fields that don't access database, as shown in the sample below:

[source,groovy]
----
@Transaction
class AController {

    @Transaction(Transaction.Policy.SKIP)
    def notRecommended() {
        ADomainClass a = new ADomainClass()
        persist(a)
        throw new RuntimeException("Suddenly fail here!")
        ADomainClass b = new ADomainClass()
        persist(b)
    }

    @Transaction(Transaction.Policy.SKIP)
    def recommended() {
        // Use it on method which doesn't require database access
        model.result = model.number1 + model.number2
    }
}
----

In the example above, +notRecommended()+ will persist +a+ in the database but not +b+ because an error was encountered
immediately after persisting +a+. This is not recommended because it will leave database in inconsistent state.